name: Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2    
      - name: Super-Linter
        uses: github/super-linter@v3.13.5
